namespace Stranichnik.Localization;

public static class UiStrings
{
    public static string AboutDialogDescription => TextResources.Get("AboutDialog_Description");
    public static string AboutDialogTitle => TextResources.Get("AboutDialog_Title");
    public static string AboutDocumentMissing => TextResources.Get("AboutDialog_DocumentMissing");
    public static string AboutDocumentReadFailed => TextResources.Get("AboutDialog_DocumentReadFailed");
    public static string AboutNoThirdPartyDocumentsMessage => TextResources.Get("AboutDialog_NoThirdPartyDocumentsMessage");
    public static string AboutNoThirdPartyDocumentsTitle => TextResources.Get("AboutDialog_NoThirdPartyDocumentsTitle");
    public static string AboutProjectLicenseTitle => TextResources.Get("AboutDialog_ProjectLicenseTitle");
    public static string AboutThirdPartyDescription => TextResources.Get("AboutDialog_ThirdPartyDescription");
    public static string AboutThirdPartyTitle => TextResources.Get("AboutDialog_ThirdPartyTitle");
    public static string ActionAddBookmark => TextResources.Get("Action_AddBookmark");
    public static string ActionAddFolder => TextResources.Get("Action_AddFolder");
    public static string ActionCopyUrl => TextResources.Get("Action_CopyUrl");
    public static string ActionDelete => TextResources.Get("Action_Delete");
    public static string ActionEdit => TextResources.Get("Action_Edit");
    public static string ActionOpen => TextResources.Get("Action_Open");
    public static string BookmarkEditorAddBookmarkTitle => TextResources.Get("BookmarkEditor_AddBookmarkTitle");
    public static string BookmarkEditorAddFolderTitle => TextResources.Get("BookmarkEditor_AddFolderTitle");
    public static string BookmarkEditorEditBookmarkTitle => TextResources.Get("BookmarkEditor_EditBookmarkTitle");
    public static string BookmarkEditorEditFolderTitle => TextResources.Get("BookmarkEditor_EditFolderTitle");
    public static string BookmarkEditorIconCurrent => TextResources.Get("BookmarkEditor_IconCurrent");
    public static string BookmarkEditorIconDefault => TextResources.Get("BookmarkEditor_IconDefault");
    public static string BookmarkEditorIconFavicon => TextResources.Get("BookmarkEditor_IconFavicon");
    public static string BookmarkEditorIconFileInvalid => TextResources.Get("BookmarkEditor_IconFileInvalid");
    public static string BookmarkEditorIconImageFiles => TextResources.Get("BookmarkEditor_IconImageFiles");
    public static string BookmarkEditorIconLabel => TextResources.Get("BookmarkEditor_IconLabel");
    public static string BookmarkEditorIconLibrary => TextResources.Get("BookmarkEditor_IconLibrary");
    public static string BookmarkEditorIconPickerTitle => TextResources.Get("BookmarkEditor_IconPickerTitle");
    public static string BookmarkEditorIconPickerUnavailable => TextResources.Get("BookmarkEditor_IconPickerUnavailable");
    public static string BookmarkEditorIconUpload => TextResources.Get("BookmarkEditor_IconUpload");
    public static string BookmarkEditorIconUploaded => TextResources.Get("BookmarkEditor_IconUploaded");
    public static string BookmarkEditorSecretBookmarkLabel => TextResources.Get("BookmarkEditor_SecretBookmarkLabel");
    public static string BookmarkEditorSecretModeNotEnabled => TextResources.Get("BookmarkEditor_SecretModeNotEnabled");
    public static string BookmarkEditorTitleLabel => TextResources.Get("BookmarkEditor_TitleLabel");
    public static string BookmarkEditorUrlLabel => TextResources.Get("BookmarkEditor_UrlLabel");
    public static string BookmarkEditorUrlPlaceholder => TextResources.Get("BookmarkEditor_UrlPlaceholder");
    public static string CommonAdd => TextResources.Get("Common_Add");
    public static string CommonCancel => TextResources.Get("Common_Cancel");
    public static string CommonClose => TextResources.Get("Common_Close");
    public static string CommonDelete => TextResources.Get("Common_Delete");
    public static string CommonMessage => TextResources.Get("Common_Message");
    public static string CommonOk => TextResources.Get("Common_OK");
    public static string CommonOff => TextResources.Get("Common_Off");
    public static string CommonOn => TextResources.Get("Common_On");
    public static string CommonSave => TextResources.Get("Common_Save");
    public static string ConfirmDeleteBookmarkTitle => TextResources.Get("Confirm_DeleteBookmarkTitle");
    public static string ConfirmDeleteFolderTitle => TextResources.Get("Confirm_DeleteFolderTitle");
    public static string ConfirmResetSecretMasterPasswordFinalMessage => TextResources.Get("Confirm_ResetSecretMasterPasswordFinalMessage");
    public static string ConfirmResetSecretMasterPasswordFinalTitle => TextResources.Get("Confirm_ResetSecretMasterPasswordFinalTitle");
    public static string ConfirmResetSecretMasterPasswordMessage => TextResources.Get("Confirm_ResetSecretMasterPasswordMessage");
    public static string ConfirmResetSecretMasterPasswordTitle => TextResources.Get("Confirm_ResetSecretMasterPasswordTitle");
    public static string ConfirmTitle => TextResources.Get("Confirm_Title");
    public static string ErrorCannotLaunchBrowser => TextResources.Get("Error_CannotLaunchBrowser");
    public static string ErrorInvalidBookmarkUrl => TextResources.Get("Error_InvalidBookmarkUrl");
    public static string ErrorOpenPageTitle => TextResources.Get("Error_OpenPageTitle");
    public static string ErrorUnsupportedBookmarkUrlScheme => TextResources.Get("Error_UnsupportedBookmarkUrlScheme");
    public static string ErrorUrlBrowserStartFailed => TextResources.Get("Error_UrlBrowserStartFailed");
    public static string IconLibraryEmpty => TextResources.Get("IconLibrary_Empty");
    public static string IconLibraryTitle => TextResources.Get("IconLibrary_Title");
    public static string LanguageDialogEnglish => TextResources.Get("LanguageDialog_English");
    public static string LanguageDialogRestartMessage => TextResources.Get("LanguageDialog_RestartMessage");
    public static string LanguageDialogRestartTitle => TextResources.Get("LanguageDialog_RestartTitle");
    public static string LanguageDialogRussian => TextResources.Get("LanguageDialog_Russian");
    public static string LanguageDialogTitle => TextResources.Get("LanguageDialog_Title");
    public static string MainMenuApp => TextResources.Get("MainMenu_App");
    public static string MainMenuAppAbout => TextResources.Get("MainMenu_App_About");
    public static string MainMenuAppExit => TextResources.Get("MainMenu_App_Exit");
    public static string MainMenuAppSettings => TextResources.Get("MainMenu_App_Settings");
    public static string MainMenuService => TextResources.Get("MainMenu_Service");
    public static string MainMenuServiceAppearance => TextResources.Get("MainMenu_Service_Appearance");
    public static string MainMenuServiceLanguage => TextResources.Get("MainMenu_Service_Language");
    public static string MainMenuServiceShowSecrets => TextResources.Get("MainMenu_Service_ShowSecrets");
    public static string RootAllBookmarks => TextResources.Get("Root_AllBookmarks");
    public static string SearchNoMatches => TextResources.Get("Search_NoMatches");
    public static string SearchPlaceholder => TextResources.Get("Search_Placeholder");
    public static string SecretSetupFailedMessage => TextResources.Get("Secret_SetupFailedMessage");
    public static string SecretSetupFailedTitle => TextResources.Get("Secret_SetupFailedTitle");
    public static string SecretUnlockRequiredMessage => TextResources.Get("Secret_UnlockRequiredMessage");
    public static string SecretUnlockRequiredTitle => TextResources.Get("Secret_UnlockRequiredTitle");
    public static string SettingsDialogTitle => TextResources.Get("Settings_Title");
    public static string SettingsSecretBookmarksDescription => TextResources.Get("Settings_SecretBookmarksDescription");
    public static string SettingsSecretBookmarksSectionTitle => TextResources.Get("Settings_SecretBookmarksSectionTitle");
    public static string SettingsSecretNewPasswordLabel => TextResources.Get("Settings_SecretNewPasswordLabel");
    public static string SettingsSecretPasswordChanged => TextResources.Get("Settings_SecretPasswordChanged");
    public static string SettingsSecretPasswordCreated => TextResources.Get("Settings_SecretPasswordCreated");
    public static string SettingsSecretPasswordRequired => TextResources.Get("Settings_SecretPasswordRequired");
    public static string SettingsSecretPasswordSaveFailed => TextResources.Get("Settings_SecretPasswordSaveFailed");
    public static string SettingsSecretPasswordsDoNotMatch => TextResources.Get("Settings_SecretPasswordsDoNotMatch");
    public static string SettingsSecretRepeatPasswordLabel => TextResources.Get("Settings_SecretRepeatPasswordLabel");
    public static string SettingsSecretResetDescription => TextResources.Get("Settings_SecretResetDescription");
    public static string SettingsSecretResetFailed => TextResources.Get("Settings_SecretResetFailed");
    public static string SettingsSecretResetNotConfigured => TextResources.Get("Settings_SecretResetNotConfigured");
    public static string SettingsSecretResetPasswordAction => TextResources.Get("Settings_SecretResetPasswordAction");
    public static string SettingsSecretResetSuccess => TextResources.Get("Settings_SecretResetSuccess");
    public static string SettingsSecretSavePasswordAction => TextResources.Get("Settings_SecretSavePasswordAction");
    public static string SettingsSecretUnlockRequired => TextResources.Get("Settings_SecretUnlockRequired");
    public static string SettingsSyncDescription => TextResources.Get("Settings_SyncDescription");
    public static string SettingsSyncConnectionFailed => TextResources.Get("Settings_SyncConnectionFailed");
    public static string SettingsSyncConnectionSucceeded => TextResources.Get("Settings_SyncConnectionSucceeded");
    public static string SettingsSyncDisabled => TextResources.Get("Settings_SyncDisabled");
    public static string SettingsSyncEnabledLabel => TextResources.Get("Settings_SyncEnabledLabel");
    public static string SettingsSyncInvalidRepository => TextResources.Get("Settings_SyncInvalidRepository");
    public static string SettingsSyncLocalOperationActive => TextResources.Get("Settings_SyncLocalOperationActive");
    public static string SettingsSyncNowAction => TextResources.Get("Settings_SyncNowAction");
    public static string SettingsSyncNowCompletedWithIssues => TextResources.Get("Settings_SyncNowCompletedWithIssues");
    public static string SettingsSyncNowFailed => TextResources.Get("Settings_SyncNowFailed");
    public static string SettingsSyncNowSucceeded => TextResources.Get("Settings_SyncNowSucceeded");
    public static string SettingsSyncNowUnavailable => TextResources.Get("Settings_SyncNowUnavailable");
    public static string SettingsSyncPasswordLabel => TextResources.Get("Settings_SyncPasswordLabel");
    public static string SettingsSyncPasswordRequired => TextResources.Get("Settings_SyncPasswordRequired");
    public static string SettingsSyncSaveAction => TextResources.Get("Settings_SyncSaveAction");
    public static string SettingsSyncSaved => TextResources.Get("Settings_SyncSaved");
    public static string SettingsSyncSectionTitle => TextResources.Get("Settings_SyncSectionTitle");
    public static string SettingsSyncRemoteUnavailable => TextResources.Get("Settings_SyncRemoteUnavailable");
    public static string SettingsSyncTestConnectionAction => TextResources.Get("Settings_SyncTestConnectionAction");
    public static string SettingsSyncUnsupportedRepositoryVersion => TextResources.Get("Settings_SyncUnsupportedRepositoryVersion");
    public static string SettingsSyncUsernameLabel => TextResources.Get("Settings_SyncUsernameLabel");
    public static string SettingsSyncUsernameRequired => TextResources.Get("Settings_SyncUsernameRequired");
    public static string SettingsSyncWebDavUrlLabel => TextResources.Get("Settings_SyncWebDavUrlLabel");
    public static string SettingsSyncWebDavUrlInvalid => TextResources.Get("Settings_SyncWebDavUrlInvalid");
    public static string SettingsSyncWebDavUrlRequired => TextResources.Get("Settings_SyncWebDavUrlRequired");
    public static string SettingsSyncWrongCredentials => TextResources.Get("Settings_SyncWrongCredentials");
    public static string SetMasterPasswordPasswordLabel => TextResources.Get("SetMasterPassword_PasswordLabel");
    public static string SetMasterPasswordPasswordRequired => TextResources.Get("SetMasterPassword_PasswordRequired");
    public static string SetMasterPasswordPasswordsDoNotMatch => TextResources.Get("SetMasterPassword_PasswordsDoNotMatch");
    public static string SetMasterPasswordRepeatPasswordLabel => TextResources.Get("SetMasterPassword_RepeatPasswordLabel");
    public static string SetMasterPasswordTitle => TextResources.Get("SetMasterPassword_Title");
    public static string SetMasterPasswordWarning => TextResources.Get("SetMasterPassword_Warning");
    public static string UnlockSecretsAction => TextResources.Get("UnlockSecrets_Action");
    public static string UnlockSecretsFailedMessage => TextResources.Get("UnlockSecrets_FailedMessage");
    public static string UnlockSecretsNotConfiguredMessage => TextResources.Get("UnlockSecrets_NotConfiguredMessage");
    public static string UnlockSecretsNotConfiguredTitle => TextResources.Get("UnlockSecrets_NotConfiguredTitle");
    public static string UnlockSecretsPasswordLabel => TextResources.Get("UnlockSecrets_PasswordLabel");
    public static string UnlockSecretsPasswordRequired => TextResources.Get("UnlockSecrets_PasswordRequired");
    public static string UnlockSecretsTitle => TextResources.Get("UnlockSecrets_Title");
    public static string AppearanceDialogDarkTheme => TextResources.Get("AppearanceDialog_DarkTheme");
    public static string AppearanceDialogLightTheme => TextResources.Get("AppearanceDialog_LightTheme");
    public static string AppearanceDialogSystemTheme => TextResources.Get("AppearanceDialog_SystemTheme");
    public static string AppearanceDialogTitle => TextResources.Get("AppearanceDialog_Title");
    public static string ValidationTitleRequired => TextResources.Get("Validation_TitleRequired");
    public static string ValidationUrlRequired => TextResources.Get("Validation_UrlRequired");

    public static string ConfirmDeleteBookmarkMessage(string title)
    {
        return TextResources.Format("Confirm_DeleteBookmarkMessage", title);
    }

    public static string ConfirmDeleteFolderMessage(string title)
    {
        return TextResources.Format("Confirm_DeleteFolderMessage", title);
    }
}
